import { Montserrat } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Header from "./components/header";
import Footer from "./components/footer";
import React from "react";
import { Transition } from "./components/transition";
config.autoAddCss = false;
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Blogging Website",
  description: "Generated by using Next Js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
